version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./observability/grafana/dashboards:/etc/grafana/dashboards
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./ecommerce-frontend/
    image: aishwaryamurahari/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    ports:
      - "3004:3004"

  backend:
    build:
      context: ./ecommerce-backend/
    image: aishwaryamurahari/ecommerce-backend:latest
    container_name: ecommerce-backend
    ports:
      - "3000:3000"

  redis:
    build: ./redis
    image: aishwaryamurahari/redis:latest
    container_name: redis
    ports:
      - "5001:5001"

  chatbot:
    build: ./ecommerce-chatbot/
    image: aishwaryamurahari/nlapi:latest
    container_name: chatbot
    ports:
      - "8004:8004"

  rabbitmq:
    build: ./message-queue/
    image: aishwaryamurahari/rabbit_mq_app:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
