version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - frontend-build
      - backend-build

jobs:
  # Frontend Build and Deploy to Docker Hub
  frontend-build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: cd ecommerce-frontend && npm install
      - run:
          name: Build Frontend
          command: cd ecommerce-frontend && npm run build
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Frontend Docker Image
          command: docker build -t aishwaryamurahari/ecommerce-frontend:1.0 ./ecommerce-frontend
      - run:
          name: Push Frontend Docker Image
          command: docker push aishwaryamurahari/ecommerce-frontend:1.0

  # Backend Build and Deploy to Docker Hub
  backend-build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: cd ecommerce-backend && npm install
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Backend Docker Image
          command: docker build -t aishwaryamurahari/ecommerce-backend:1.0 ./ecommerce-backend
      - run:
          name: Push Backend Docker Image
          command: docker push aishwaryamurahari/ecommerce-backend:1.0
