global:
  scrape_interval: 15s # Default scrape interval for all jobs (15 seconds)
  evaluation_interval: 15s # How often Prometheus evaluates rules

scrape_configs:
  - job_name: 'nodejs'
    scrape_interval: 10s # Custom scrape interval for this job
    static_configs:
      - targets: ['host.docker.internal:3000']
