global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    scrape_interval: 10s # Custom scrape interval for this job
    static_configs:
      - targets: ['host.docker.internal:3000']
